# Generated by Django 2.2.1 on 2019-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(related_name='accounts', to='app.Account'),
        ),
        migrations.AddField(
            model_name='user',
            name='currencies',
            field=models.ManyToManyField(related_name='currencies', to='app.Currency'),
        ),
    ]
